CREATE TABLE `minutes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `InvID` varchar(16) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ETotal` decimal(7,1) NOT NULL DEFAULT '-1.0',
  `EToday` decimal(4,2) NOT NULL DEFAULT '-1.00',
  `Temp` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `HTotal` int(8) NOT NULL DEFAULT '-1',
  `VPV1` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `VPV2` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `VPV3` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `IPV1` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `IPV2` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `IPV3` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `VAC1` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `VAC2` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `VAC3` decimal(4,1) NOT NULL DEFAULT '-1.0',
  `IAC1` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `IAC2` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `IAC3` decimal(3,1) NOT NULL DEFAULT '-1.0',
  `FAC1` decimal(4,2) NOT NULL DEFAULT '-1.00',
  `FAC2` decimal(4,2) NOT NULL DEFAULT '-1.00',
  `FAC3` decimal(4,2) NOT NULL DEFAULT '-1.00',
  `PAC1` int(11) NOT NULL DEFAULT '-1',
  `PAC2` int(11) NOT NULL DEFAULT '-1',
  `PAC3` int(11) NOT NULL DEFAULT '-1',
  `ServerStamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
